#pragma once
#include "sdkconfig.h"

// Fallback defaults so sources compile even if Kconfig symbols are missing.
#ifndef CONFIG_GIMBAL_I2C_SDA_GPIO
#define CONFIG_GIMBAL_I2C_SDA_GPIO 8
#endif
#ifndef CONFIG_GIMBAL_I2C_SCL_GPIO
#define CONFIG_GIMBAL_I2C_SCL_GPIO 9
#endif
#ifndef CONFIG_GIMBAL_I2C_FREQ_HZ
#define CONFIG_GIMBAL_I2C_FREQ_HZ 400000
#endif
#ifndef CONFIG_GIMBAL_BNO08X_ADDR
#define CONFIG_GIMBAL_BNO08X_ADDR 0x4A
#endif
#ifndef CONFIG_GIMBAL_BNO08X_INT_GPIO
#define CONFIG_GIMBAL_BNO08X_INT_GPIO -1
#endif
#ifndef CONFIG_GIMBAL_BNO08X_INT_ACTIVE_LOW
#define CONFIG_GIMBAL_BNO08X_INT_ACTIVE_LOW 1
#endif
#ifndef CONFIG_GIMBAL_BNO08X_SPI_MODE
#define CONFIG_GIMBAL_BNO08X_SPI_MODE 0
#endif
#ifndef CONFIG_GIMBAL_BNO08X_SPI_TRACE
#define CONFIG_GIMBAL_BNO08X_SPI_TRACE 0
#endif
#ifndef CONFIG_GIMBAL_BNO08X_WAKE_GPIO
#define CONFIG_GIMBAL_BNO08X_WAKE_GPIO -1
#endif
#ifndef CONFIG_GIMBAL_BNO08X_RST_GPIO
#define CONFIG_GIMBAL_BNO08X_RST_GPIO -1
#endif
#ifndef CONFIG_GIMBAL_SERVO_GPIO
#define CONFIG_GIMBAL_SERVO_GPIO 10
#endif
#ifndef CONFIG_GIMBAL_BUTTON_GPIO
#define CONFIG_GIMBAL_BUTTON_GPIO 1
#endif

#ifndef CONFIG_GIMBAL_UART_RVC_SNIFFER
#define CONFIG_GIMBAL_UART_RVC_SNIFFER 0
#endif
#ifndef CONFIG_GIMBAL_UART_PORT
#define CONFIG_GIMBAL_UART_PORT 1
#endif
#ifndef CONFIG_GIMBAL_UART_RX_GPIO
#define CONFIG_GIMBAL_UART_RX_GPIO 0
#endif
#ifndef CONFIG_GIMBAL_UART_TX_GPIO
#define CONFIG_GIMBAL_UART_TX_GPIO -1
#endif
#ifndef CONFIG_GIMBAL_UART_BAUD
#define CONFIG_GIMBAL_UART_BAUD 115200
#endif
